### ISSUE TITLE
Findings Resource Page

### ISSUE THREAD

**Issue by MeggieHarvey** [gulfofmaine/curriculum-platform#125]
**Describe the bug**
When I click on Findings from the Field from the tab at the top of the home page, no curriculum appears on the page. There are 4 resources tagged with the program "Findings from the Field" that are not appearing. 

**To Reproduce**
1. Go to 'teach.gmri.org'
2. Click on 'Resources'
3. Scroll down to 'Findings from the Field'
4. See that no curriculum comes up associated with Findings. 

**Expected behavior**
All curriculum resources that are tagged with the program "Findings from the Field" should appear. Note: if you go to "Browse All Content" and select the filter "Findings from the Field" you are able to view all Findings resources. 

**Screenshots**
![Screen Shot 2021-01-05 at 11 06 42 AM](https://user-images.githubusercontent.com/77014697/103669289-2743ec80-4f46-11eb-8020-06a61dcc56cc.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 11.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greatwhiteape** [comment]
I was able to resolve this in the CMS. The findings page was originally created as a copy page. I needed to delete it, and recreate it as a "Search" page. That allowed the tag for the search functionality.
