### ISSUE TITLE
Type of Lesson filter

### ISSUE THREAD

**Issue by MeggieHarvey** [gulfofmaine/curriculum-platform#126]
**Describe the bug**
We do not need a filter for "Type of Lesson". Please remove this option from the filters under the Browse Content Page.

**To Reproduce**
1. Go to 'Browse All Content'
2. Scroll down to 'Type of Lesson'

**Expected behavior**
No "Type of Lesson" filter needed. 

**Screenshots**
![Screen Shot 2021-01-05 at 11 17 39 AM](https://user-images.githubusercontent.com/77014697/103670547-b3a2df00-4f47-11eb-9a74-47af497743ab.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 11.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greatwhiteape** [comment]
Done (in one of the previous PR's. I can't remember which one.)
