### ISSUE TITLE
Information in Overview tab for Modules

### ISSUE THREAD

**Issue by MeggieHarvey** [gulfofmaine/curriculum-platform#127]
**Describe the bug**
We would like both Learning Space and Topic/Keyword to be visible in the overview tab on all modules. You can see a list of information we would like to have on the overview tab under the "Module Landing pages organization" tab in this spreadsheet: https://docs.google.com/spreadsheets/d/1BgbFCKvFRk9JYZl_DUJKjZbDiY2mWkeQVbn5NupWEkw/edit?usp=sharing

We would also like to REMOVE the "link student page in google classrooms" option, as we don't have google classroom accounts. 

**To Reproduce**
1. Go to 'Browse All Content'
2. Click on any module. 
3. Scroll down to the Overview tab. 
4. See errors.

**Expected behavior**
Information we would like on this tab includes: 
Time Estimate (done)
Audience (done)
Learning space (needed)
Topic/Key words (needed)
Standards Alignment
NO link to google classroom page

**Screenshots**
![Screen Shot 2021-01-05 at 11 30 16 AM](https://user-images.githubusercontent.com/77014697/103671804-69226200-4f49-11eb-9def-fdf6a6d00b87.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 11.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MeggieHarvey** [comment]
To clarify, we would like the ability to hide the "link to student pages in google classroom" if no information is included on the student page.

**Comment by greatwhiteape** [comment]
@youngmorse @MeggieHarvey The keyword half of this will be a bigger issue. I had removed that functionality last fall, at the request of the EDU group.

**Comment by MeggieHarvey** [comment]
@greatwhiteape Not sure if I just used the wrong terminology. Is adding the existing "topic" tags to the overview page also a challenge? I meant "topic" when I wrote "keyword"
