### ISSUE TITLE
Part vs Lessons inconsistency in Professional Learning Modules

### ISSUE THREAD

**Issue by MeggieHarvey** [gulfofmaine/curriculum-platform#129]
**Describe the bug**
On mobile app view, the 3rd tab in Professional Learning Modules is labelled "Lessons". This should be "Parts" so that it is consistent with web browser view. We would also like the second tab to read "Details" 

**To Reproduce**
1. Go to 'Browse All Content'
2. Click on 'Professional Learning' filter
3. Select any Professional Learning Module
3. See the labels for the each of the three tabs "Overview", "Key Considerations" and "Details"
4. Resize the web browser, so it is long and narrow. 
5. See error: Three sections are now labelled "Overview" "Key Considerations" and "Lessons"

**Expected behavior**
In both instances, the three sections should be called "Overview" "Details" and "Parts" 

**Screenshots**
![Screen Shot 2021-01-05 at 11 45 13 AM](https://user-images.githubusercontent.com/77014697/103673917-1e561980-4f4c-11eb-9e97-30b101a9ea2e.png)
![Screen Shot 2021-01-05 at 11 44 55 AM](https://user-images.githubusercontent.com/77014697/103673947-2910ae80-4f4c-11eb-9aed-d459f08deeac.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 
 - Version: 11.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greatwhiteape** [comment]
Resolved in PR #135
