### ISSUE TITLE
Filter by standards not functional

### ISSUE THREAD

**Issue by MeggieHarvey** [gulfofmaine/curriculum-platform#132]
**Describe the bug**
When I select a standard from the standards filter, the list of resources remains unchanged. I have been tagging all curriculum resources with standards. 
Also, there is a standard labeled "Don't use" in the published list. When I try to delete it, I get an error message. 
  
**To Reproduce**
1. Go to 'Browse all content'
2. Click on 'Filter by Standards' (Note that a standard labeled ("Don't use") is in this list. 
3. Select any standard
4. Click 'close'
5. See that the list of resources is unchanged.

**Expected behavior**
The list should be filtered to include only resources tagged with the standard selected.  The "Don't use" standard should not be visible in the list. 

**Screenshots**
![Screen Shot 2021-01-08 at 9 24 19 AM](https://user-images.githubusercontent.com/77014697/104025976-59965980-5193-11eb-9037-5b9ef8c51194.png)

Error message when I try to delete the "Don't use" standard: 
![Screen Shot 2021-01-08 at 9 25 35 AM](https://user-images.githubusercontent.com/77014697/104026121-8480ad80-5193-11eb-8c7f-9aa0485edf52.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 11.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greatwhiteape** [comment]
This is resolved. The Hemlock Wolly Adelgid and Research Article modules had an empty standard set up in each. That was causing the sorting system to crash. Removing the blank Standard entry resolved the issue. 
![Screenshot from 2021-01-11 10-18-51](https://user-images.githubusercontent.com/393805/104200567-d5dca700-53f6-11eb-8cf1-926506217a4e.png)
